### ISSUE TITLE
Colors configuration?

### ISSUE THREAD

**Issue by xDShot** [Electrux/ls_extended#21]
Can I change text colors somehow? Is there a config for editing?

**Comment by Chirag-Khandelwal** [comment]
the text colors can be changed by changing your terminal color scheme since the code uses that only and not any special colors :)

**Comment by Chirag-Khandelwal** [comment]
closing this for now

**Comment by xDShot** [comment]
This is illogical. Why should I change global color configuration affecting others applications?

**Comment by Chirag-Khandelwal** [comment]
because that is how most terminal applications work. They change colors based on terminal's color. Vi, Nano, package managers, etc. all work that way.
