### ISSUE TITLE
Homebrew formula 

### ISSUE THREAD

**Issue by MaT1g3R** [Electrux/ls_extended#26]
It would be nice to have a homebrew formula for ls_extended

**Comment by Chirag-Khandelwal** [comment]
That is true. If u want, you can create one. I can't right now due to my real life obligations. Once i am a bit free, I will work on it :)
Thanks for the suggestion!

**Comment by Chirag-Khandelwal** [comment]
Ok, The homebrew formula has been created. To use it perform the following:
* `brew tap Electrux/homebrew-taps`
* `brew install ls_extended`

And you should be good to go! The binary should be installed as `ls_extended` and that will be the command to use it.
Please do tell if you encounter any issues. Thanks!
