### ISSUE TITLE
ISO date format

### ISSUE THREAD

**Issue by FunctionalHacker** [Electrux/ls_extended#28]
Please add support for ISO 8601 date format. In regular ls, this is enabled with `--time-style=long-iso`. Below I have pasted an example what happens currently with regular ls and ls_extended.

```
~/test
❯ /usr/bin/ls -l --time-style=long-iso
total 0
-rw-r--r-- 1 reekymarko users 0 2018-09-30 17:32 file1
-rw-r--r-- 1 reekymarko users 0 2018-09-30 17:32 file2

~/test
❯ /usr/bin/ls_extended -l --time-style=long-iso
 4063667     -rw-r--r--		1	reekymarko	users	0B	Sep 30 15:32	 file1
 4063668     -rw-r--r--		1	reekymarko	users	0B	Sep 30 15:32	 file2
```

**Comment by Chirag-Khandelwal** [comment]
Right now, it's kinda hard for me to get time to work on it, but I will do so as soon as I can. Thanks! :)

**Comment by FunctionalHacker** [comment]
I totally understand :+1: I might have a crack at it myself at some point if I find the time.

**Comment by Chirag-Khandelwal** [comment]
Implemented using `-I` option (no support for long options yet) 😅😁
