### ISSUE TITLE
More sorting options?

### ISSUE THREAD

**Issue by ryanerwin** [Electrux/ls_extended#32]
This looks really fantastic! Just installed today... Really a brilliant idea!

Curious if you've considered supporting some of the GNU ls sort options?

Personally the ones I use all the time are:

```
lsdate=ls -tr # sort by modified time, newest last (since -r reverses list)
lssize=ls -Sr # sort by size, largest last
lstype=ls -X # sort by extension... would be cooler than ever with icons!
````

Reference:
```
       -t     sort by modification time, newest first
       -S     sort by file size, largest first
       -X     sort alphabetically by entry extension
       -r, --reverse
              reverse order while sorting
```

**Comment by Chirag-Khandelwal** [comment]
sorry for the delay, i am kinda busy right now. i shall work on it in the near future :).
sounds like a great idea :D

**Comment by Chirag-Khandelwal** [comment]
hey! this has been implemented (not the long option --reverse though).
Please do try it and see if it works for you. :)

Also, thanks for the kind words 😄
