### ISSUE TITLE
Feature request: Trim some whitespace to make output more compact

### ISSUE THREAD

**Issue by Tobbe** [Electrux/ls_extended#37]
First of all, thank you for writing ls_extended. It makes the ls output both nicer to look at **and** more efficient to work with!

This is ls_extended compared to regular ls

![image](https://user-images.githubusercontent.com/30793/137564899-7b638286-7e7c-4cde-b8d1-f89ade676e01.png)

Would it be possible to have less space around the username and the group? And also around the hard link count. When working in a split screen I often get files wrapping to the next line when they would easily have fit on one line had the output just been a bit more compact (more like the regular ls output)

**Comment by Chirag-Khandelwal** [comment]
Hey! Thanks for the kind words! :)
This is actually weird. It shouldn't add that much space.
I am not able to replicate it.
Which build of the program are you using?
That looks like an older code's build actually.

**Comment by Chirag-Khandelwal** [comment]
![My output (uses latest master branch)](https://user-images.githubusercontent.com/18194713/137572353-643aa699-8a83-4920-ad22-7d1bf025201d.png)

**Comment by Tobbe** [comment]
Wow, yeah, yours is much more compact! :)  I installed using homebrew on my M1 MacBook Pro

**Comment by Tobbe** [comment]
![image](https://user-images.githubusercontent.com/30793/137579230-cd029293-e699-4ab3-bec3-3f47d0b2e108.png)

**Comment by Tobbe** [comment]
Noticed you just released a new version, so I tried to update

![image](https://user-images.githubusercontent.com/30793/137579419-71f5e559-0991-4504-b9cc-f20a4ae0a980.png)

Still have the same 1.0.8 version with the same behavior I posted above

**Comment by Chirag-Khandelwal** [comment]
Oh okay, yes apologies, I had forgotten to update the homebrew version.
That has been done now.
Could you please uninstall ls_extended, update homebrew formula, and reinstall ls_extended?
The archive has just been updated - archive name will be `v1.tar.gz`
Version will be `1.0.0`

**Comment by Tobbe** [comment]
After uninstalling and updating I get this error when I try to reinstall

```
==> Downloading https://github.com/Electrux/ls_extended/archive/refs/tags/v1.tar.gz
Already downloaded: /Users/tobbe/Library/Caches/Homebrew/downloads/ccef4579e792c33b5d4f0664ef18adf920fab39035a71d7727c39b2aa60ef651--ls_extended-1.tar.gz
Error: ls_extended: SHA256 mismatch
Expected: c6af08877e889fe0732f25f7e6f850c7816cf7788fee191bcc80dbf1288b3740
  Actual: c751e8198356cbbbbfe6191a6dd379d0525fea469299355ac8331090f2db63fe
    File: /Users/tobbe/Library/Caches/Homebrew/downloads/ccef4579e792c33b5d4f0664ef18adf920fab39035a71d7727c39b2aa60ef651--ls_extended-1.tar.gz
To retry an incomplete download, remove the file above.
```

I tried deleting the file, as it says to do, but I get the same error again when I try to install

**Comment by Tobbe** [comment]
I created a PR for the sha https://github.com/Electrux/homebrew-taps/pull/1

**Comment by Chirag-Khandelwal** [comment]
Merged the PR (thanks a bunch!).
Let me know if it works after that.

**Comment by Tobbe** [comment]
Before and after 👍 

![image](https://user-images.githubusercontent.com/30793/137602859-2f22d85c-9635-4b12-bd88-f8fa131cb9c1.png)

**Comment by Chirag-Khandelwal** [comment]
Awesome! Closing this issue.
Have a good one! :)
