### ISSUE TITLE
Using actual /bin dir

### ISSUE THREAD

**Issue by aphive** [Electrux/ls_extended#38]
Not an issue just a question. Instead of building this in the repo's bin dir. Is there a way to make this install it in the actual /bin. dir?   Am I able to just move the ls_extended dir that was generated into /bin or does it need more work and configuration for that to work.

**Comment by Chirag-Khandelwal** [comment]
Hi @aphive
You just need to copy/move the `ls_extended` file generated in the repo's bin directory to wherever you want to place it (including `/bin`). Nothing more to it :)
