### ISSUE TITLE
ls_extended Behavior with sudo cp Results in Unexpected Output

### ISSUE THREAD

**Issue by cross-sniper** [Electrux/ls_extended#39]
I've noticed an unexpected behavior with the ls_extended binary when it's copied to /usr/local/bin/ls using the sudo cp command. Instead of behaving like the standard ls command, it outputs the contents of a folder as if it was invoked with the -l option.

Steps to Reproduce:

Download and compile the ls_extended binary.
Copy the ls_extended binary to /usr/local/bin/ls using the following command:
```shell
sudo cp ls_extended /usr/local/bin/ls
```
Navigate to a directory with subdirectories and files.
Run the ls command in the directory.
Observe the output, which is different from the expected behavior of the standard ls command.

Expected Behavior:
The ls command, when invoked after copying ls_extended to /usr/local/bin/ls, should display a basic list view of files and directories, similar to the standard ls command, without the -l option.

Actual Behavior:
The ls command, after copying ls_extended to /usr/local/bin/ls, is displaying the contents of a folder as if it was invoked with the -l option, which includes detailed information about files and directories.

Additional Information:

    ls_extended Version:  1.0
    Operating System: linux mint

Screenshots/Additional Context:

![image](https://github.com/Electrux/ls_extended/assets/137736431/40e47209-c63c-49bd-b999-c00de8d05716)
Note: Please let me know if there is any specific configuration or behavior-related information that would help diagnose and resolve this issue.

**Comment by Chirag-Khandelwal** [comment]
Hi!
This is a weird issue which should not be happening.
Can you confirm if you have an alias for the ls command which may be having the `-l` option? I have seen the default shell startup scripts containing such aliases. You can check this with the command `alias ls`.
When you directly run the `/usr/bin/ls` command, it doesn't use any aliases so the command work exactly how it's supposed to be. You can also try doing the same with `/usr/local/bin/ls_extended`.

**Comment by cross-sniper** [comment]
I copied the binary to `/usr/local/bin/ls`, and made another copy to `/usr/local/bin/ls-l`, the `ls-l` works fine

![image](https://github.com/Electrux/ls_extended/assets/137736431/3c68252a-d382-43e4-bae8-88d194a52352)

the `ls` does not

![image](https://github.com/Electrux/ls_extended/assets/137736431/68dd075e-8893-4cd8-842c-d9898d67e43c)


i have no alias on my bashrc
and this is the `which` command output

![image](https://github.com/Electrux/ls_extended/assets/137736431/419f5f36-12f0-4a54-9c87-c8a9a3172103)


Thanks in advance

**Comment by Chirag-Khandelwal** [comment]
The alias doesn't have to be in bashrc. But since `ls-l` worked correctly, so should `ls` itself. Did you try the `alias ls` command? What was the output?
Also, what happens when you remove the ls_extended binary from /usr/local/bin and just use the normal `ls` command?

**Comment by cross-sniper** [comment]
the output of `alias ls` is `alias ls='ls --color=auto'`

**Comment by Chirag-Khandelwal** [comment]
Oh LOL that's exactly why this issue is happening. `ls_extended` does not take into consideration invalid arguments and just reads the relevant symbols from them. So as far as `ls_extended` is concerned, `ls --color=auto` contains the `l` which is required for vertical listing. 😂 
Created a fix for it which is committed now. Pull, rebuild, and try again! 😀

**Comment by cross-sniper** [comment]
Thank you so much for identifying the issue and creating a fix! 😄 It's good to know that ls_extended was interpreting the arguments differently, and I appreciate your quick response in resolving this.

I've pulled the latest changes, rebuilt ls_extended, and gave it a try. Everything is working as expected now, and ls_extended behaves just like the standard ls command when copying it to /usr/local/bin/ls. The issue is resolved on my end!

Thanks again for your prompt support and for addressing this issue. Your work is much appreciated! 👍

**Comment by Chirag-Khandelwal** [comment]
No problem! Thanks for describing the issue!
Happy to help, and enjoy!! :)

**Comment by demonfleed** [comment]
hi,
great work, easy to install and very well written. I'm using it under Mac OS Sonoma, iTerm2 and JetBrainsMono Nerd Font Mono.
Having the problem that some icons were wrong (I tried different fonts to solve, but nothing...) I modified the icons.c file using the ones used in nvim tree.
If you think it can be usefull I can send the modified file.
bye and thank you for your work!

**Comment by Chirag-Khandelwal** [comment]
@demonfleed i’d recommend creating a new issue and pasting the before and after screenshots of ur changes - for me to understand best what is being updated. If u already have the change created, best to create a merge request with the screenshots.
Glad you liked the software though!
