### ISSUE TITLE
`gcvt` not present on some OS's

### ISSUE THREAD

**Issue by kaosatha** [Electrux/ls_extended#4]
`ls_extended` calls `gcvt` at src/core.c:120. On some OS's (FreeBSD for instance) `gcvt` is unavailable. Is there any reason `gcvt` is used over `snprintf`? I have a fork with the change made, if this is something that would be considered for merging?

**Comment by Chirag-Khandelwal** [comment]
oh I didn't know FreeBSD doesn't have gcvt! I would love to merge that change if you have made! Go ahead and Pull Request it. Thanks a lot 😄 👍

**Comment by Chirag-Khandelwal** [comment]
fixed
