### ISSUE TITLE
ls_extended * problem

### ISSUE THREAD

**Issue by qqldd** [Electrux/ls_extended#5]
I have two problems:

1. ls_extended file.*  returns " "Unable to open directory: file.txt/"
2. ls_extended * returns the last file from ls *

**Comment by qqldd** [comment]
I probably see why. The problem for 1 could be:

`ls_extended file.txt` returns Unable to open directory: file.txt/

So the ls_extended expects the argument to be a directory, right?

**Comment by Chirag-Khandelwal** [comment]
yes, I will work on getting the correct output. thanks for telling :)

**Comment by Chirag-Khandelwal** [comment]
okay the argument part has been fixed. Using a file as argument now works. The *, however, will still not work because it does not accept multiple arguments pertaining to files. Will work on that.

**Comment by Chirag-Khandelwal** [comment]
version 1.0.6 resolves this, and has been added to the master branch. please test it :)

**Comment by qqldd** [comment]
Yes, it is working! Thanks @Electrux !

**Comment by Chirag-Khandelwal** [comment]
awesome! thanks! 😄
