### ISSUE TITLE
Alignment with variant length of group name

### ISSUE THREAD

**Issue by qqldd** [Electrux/ls_extended#7]
If the group name length one is <8, another one is >8. The tab alignment is not working, it will output like:

```
 -rw-r-----     1       qqldd      self     54B     May 26 06:53      configs_dir.sh
 drwxr-x---     2       qqldd      longnamegroup    4096B   Jun 12 18:30      crontab
```

**Comment by Chirag-Khandelwal** [comment]
well, for these cases, some code will have to be changed. Basically, we need to find string length of every group that is there. It will take some (kinda) major change in design. I will think of how to implement it. Thanks a lot :)

By the way, does the default **ls** command work correctly in this situation?

**Comment by qqldd** [comment]
Yes, the default **ls** magically works as:
```
-rw-r----- 1 qqldd self            54 May 25  2017 configs_dir.sh
drwxr-x--- 2 qqldd longnamegroup 4.0K Jun 12 11:30 crontab
```
I also find that the ls_extended uses UTC while default ls uses my timezone. I don't know if this works as intended. :smile:

**Comment by Chirag-Khandelwal** [comment]
oh... yes I think I forgot about UTC honestly haha.. My bad. And ok, I will try fixing this as soon as I can... it will take a fair bit of change 😅 
thanks a lot :)

**Comment by Chirag-Khandelwal** [comment]
this should now work correctly from 58815c4728838ac164468168486e1483d08dcd05
please reopen if it doesn't :)
