### ISSUE TITLE
ls spacing is sometimes messed up

### ISSUE THREAD

**Issue by MaT1g3R** [Electrux/ls_extended#9]
Sometimes a single file is broken up into two lines

![screen shot 2018-06-13 at 2 37 57 pm](https://user-images.githubusercontent.com/15258494/41334342-e187cc86-6f17-11e8-80c5-9106b670bd0a.png)

**Comment by Chirag-Khandelwal** [comment]
please test and verify if it is fixed and thanks a lot for pointing that out :)

**Comment by MaT1g3R** [comment]
Thank you, it seems to be fixed

**Comment by Chirag-Khandelwal** [comment]
awesome! thanks a lot for the help :)

**Comment by jhonnold** [comment]
I'm able to recreate this issue if the longest file is at the end of the line

<img width="1052" alt="screen shot 2018-07-17 at 8 20 15 am" src="https://user-images.githubusercontent.com/25160789/42819846-4cee7604-899a-11e8-9a96-193e550d6e30.png">

Seems to be coming from here:
```c
// ls.c (line 98)
int max_items_per_line = ( int ) ( ws->ws_col - 1 ) / ( max_len_in_files - 14 );
```
It seems your colors in `colors.c` are all 7 bits, but maybe when padding it only uses the 6 bits at the end?

I couldn't recreate this issue when using either `- 13` or `- 12`. However, I do suspect 13 will still allow the issue in very rare cases I just can't find any.
